version: "3.9"
services:
    db:
        container_name: "db_container"
        build:
          context: .
          dockerfile: ./dockerfile_db.dockerfile
        ports:
        - 5431:5431
        networks:
            - app-tier
        hostname: postgres
    new_app:
        container_name: "app"
        build:
          context: .
          dockerfile: ./docker_application.dockerfile
        depends_on:
          - db
        networks:
          - app-tier
        ports:
        - 5000:5000

networks:
  app-tier:
    driver: bridge
